# Generated by Django 4.0.4 on 2022-09-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u_session',
            name='uId',
        ),
        migrations.AddField(
            model_name='u_session',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
